[phases.setup]
nixPkgs = ["nodejs_22"]

[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.build]
cmd = "npm install --legacy-peer-deps && npx prisma generate && npm run build"

[phases.start]
cmd = "npx prisma generate && node dist/server.js"
